---
- name: Test Windows Connectivity
  hosts: dc01.example.lab
  gather_facts: true
  tasks:
    - name: Get ComputerSystem Information
      ansible.windows.win_shell: Get-CimInstance -ClassName Win32_ComputerSystem
      register: computer_system_info
    - name: Display
      ansible.windows.win_shell: |
        $info = @{
          "Name" = "{{ computer_system_info.stdout | from_json | json_query('Name') }}"
          "Domain" = "{{ computer_system_info.stdout | from_json | json_query('Domain') }}"
          "Manufacturer" = "{{ computer_system_info.stdout | from_json | json_query('Manufacturer') }}"
          "Model" = "{{ computer_system_info.stdout | from_json | json_query('Model') }}"
        }
        $info | Format-Table -AutoSize
