---
- name: Test Windows Connectivity
  hosts: dc01.example.lab
  gather_facts: true
  tasks:
    - name: Get ComputerSystem Information
      ansible.windows.win_shell: Get-CimInstance -ClassName Win32_ComputerSystem
      register: computer_system_info
